sudo: require

service:
  - docker

before_install:
  - docker build -t r4ncid/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t r4ncid/api-test -f ./api/Dockerfile.dev ./api
  - docker build -t r4ncid/worker-test -f ./worker/Dockerfile.dev ./worker

script:
  - docker run -e CI=true r4ncid/react-test yarn test
  - docker run r4ncid/api-test yarn test
  - docker run r4ncid/worker-test yarn test