sudo: require

service:
  - docker

before_install:
  - docker build -t r4ncid/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t r4ncid/api-test -f ./api/Dockerfile.dev ./api
  - docker build -t r4ncid/worker-test -f ./worker/Dockerfile.dev ./worker

script:
  - docker run -e CI=true r4ncid/react-test yarn test
  - docker run r4ncid/api-test yarn test
  - docker run r4ncid/worker-test yarn test


after_success:
  #Build the docker file
  - docker build -t r4ncid/multi-client ./client
  - docker build -t r4ncid/multi-api ./api
  - docker build -t r4ncid/multi-worker ./worker
  - docker build -t r4ncid/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  - docker push r4ncid/multi-client
  - docker push r4ncid/multi-api
  - docker push r4ncid/multi-worker
  - docker push r4ncid/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-975946885998
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"