version: '3'
services: 
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./api:/app
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - 3050:80
    restart: always